### ISSUE TITLE
tokenizer utf-8 support

### ISSUE THREAD

**Issue by IWANABETHATGUY** [postcss-rs/postcss-rs#77]

**Comment by CGQAQ** [comment]
I think tokenizer *should* support UTF-8 already, 'cause tokens are extracted from valid UTF-8 string and split by boundary chars like ASCII whitespaces, quotes, parentheses, and other ASCII chars.
If split chars are ASCII chars(which is u8) and contents split by these ASCII chars are also valid UTF-8, we should support UTF-8 already. @justjavac  @IWANABETHATGUY

**Comment by IWANABETHATGUY** [comment]
> I think tokenizer _should_ support UTF-8 already, 'cause tokens are extracted from valid UTF-8 string and split by boundary chars like ASCII whitespaces, quotes, parentheses, and other ASCII chars. If split chars are ASCII chars(which is u8) and contents split by these ASCII chars are also valid UTF-8, we should support UTF-8 already. @justjavac @IWANABETHATGUY

should add some non-ascii test  to validate .

**Comment by CGQAQ** [comment]
> > I think tokenizer _should_ support UTF-8 already, 'cause tokens are extracted from valid UTF-8 string and split by boundary chars like ASCII whitespaces, quotes, parentheses, and other ASCII chars. If split chars are ASCII chars(which is u8) and contents split by these ASCII chars are also valid UTF-8, we should support UTF-8 already. @justjavac @IWANABETHATGUY
> 
> should add some non-ascii test to validate .

The question is what chars to test, and how many is enough

**Comment by CGQAQ** [comment]
Here are some situations that can have non-ascii I can come up with
1. Quoted string (content: '')
2. Identifier(class name)

What we looking for quoted string is just some chars inside quotes, which should not need to test. A identifier is some chars in between some whitespaces, which should not need to test as well

**Comment by IWANABETHATGUY** [comment]
closed via https://github.com/postcss-rs/postcss-rs/pull/91
